### ISSUE TITLE
Error on Sanity studio

### ISSUE THREAD

**Issue by Gr33nLight** [sanity-io/nextjs-blog-cms-sanity-v3#189]
Hello, following the basic setup, after logging in into Sanity studio and going to the /studio/desk path and clicking in the "Settings" menu option I get the following error

![SCR-20230117-oj8](https://user-images.githubusercontent.com/7921724/212959069-5b9c4c8e-05a8-4e3a-9756-5822642da361.png)

```
Error: (0 , s.cache) is not a function
TypeError: (0 , s.cache) is not a function
    at 37476 (https://blog-nextjs-sanity-topaz-nine.vercel.app/_next/static/chunks/476.fb6facffda517aa9.js:1:547)
    at Function.l (https://blog-nextjs-sanity-topaz-nine.vercel.app/_next/static/chunks/webpack-a7d003a4ba84ccd7.js:1:167)

```

In Vercel build logs I get errors like:

```
warn  - Compiled with warnings
./schemas/settings/OpenGraphPreview.tsx
Attempted import error: 'cache' is not exported from 'react' (imported as 'cache').
```

After some testing  it seems like the error is caused by the cache() function

No changes to the template were made, just cloned and launched the base version.

Tried both installing deps with yarn and npm

Website is deployed to Vercel

**Comment by Gr33nLight** [comment]
This is related to #185 closing
